-- This migration file is empty on purpose.
-- It manages new views, procedures and functions, that are stored in /db/migration/objects
-- Here is the list of these objects
-- -- view_systems
-- -- view_characters
-- -- view_quests
-- -- get_systems
-- -- get_characters
-- -- get_quests
