
DELETE FROM image_types WHERE name = 'Default';
UPDATE "image_types" SET id = 1 WHERE name = 'User avatar';
UPDATE "image_types" SET id = 2 WHERE name = 'World Header';
UPDATE "image_types" SET id = 3 WHERE name = 'World Avatar';
UPDATE "image_types" SET id = 4 WHERE name = 'Location Image';
UPDATE "image_types" SET id = 5 WHERE name = 'Race Image';
UPDATE "image_types" SET id = 6 WHERE name = 'Item Image';
UPDATE "image_types" SET id = 7 WHERE name = 'Skill Image';
UPDATE "image_types" SET id = 8 WHERE name = 'Character Portrait';
UPDATE "image_types" SET id = 9 WHERE name = 'Map Image';
UPDATE "image_types" SET id = 10 WHERE name = 'Background Image';

-- Alter images table
ALTER TABLE "images" RENAME COLUMN "url" TO "address";
ALTER TABLE "images"
    ADD COLUMN "width" int NOT NULL DEFAULT 0,
    ADD COLUMN "height" int NOT NULL DEFAULT 0,
    DROP COLUMN "img_guid",
    DROP COLUMN "base_url";

CREATE SEQUENCE IF NOT EXISTS image_types_id_seq
    START WITH 11
    INCREMENT BY 1;

--return identity column
ALTER TABLE images DROP CONSTRAINT images_image_type_id_fkey; --drop FK key
ALTER TABLE "image_types" DROP CONSTRAINT IF EXISTS image_types_id_uniq;
ALTER TABLE "image_types" ADD COLUMN "new_id" INT GENERATED BY DEFAULT AS IDENTITY;
UPDATE "image_types" SET "new_id" = "id";
ALTER TABLE "image_types" DROP COLUMN "id";
ALTER TABLE "image_types" RENAME COLUMN "new_id" TO "id";
ALTER TABLE "image_types" ADD CONSTRAINT image_types_id_uniq UNIQUE ("id");
ALTER TABLE "images" ADD CONSTRAINT images_image_type_id_fkey FOREIGN KEY ("image_type_id") REFERENCES "image_types"("id"); --return FK key

-- Alter image_types table
ALTER TABLE "image_types"
    ADD COLUMN "width" int,
    ADD COLUMN "height" int,
    DROP COLUMN "variant";

DROP TYPE image_variant;

UPDATE "image_types" SET width = 150, height = 150 WHERE name = 'User avatar';
UPDATE "image_types" SET width = 1000, height = 200 WHERE name = 'World Header';
UPDATE "image_types" SET width = 200, height = 200 WHERE name = 'World Avatar';
UPDATE "image_types" SET width = 800, height = 600 WHERE name = 'Location Image';
UPDATE "image_types" SET width = 300, height = 300 WHERE name = 'Race Image';
UPDATE "image_types" SET width = 100, height = 100 WHERE name = 'Item Image';
UPDATE "image_types" SET width = 100, height = 100 WHERE name = 'Skill Image';
UPDATE "image_types" SET width = 150, height = 150 WHERE name = 'Character Portrait';
UPDATE "image_types" SET width = 1200, height = 800 WHERE name = 'Map Image';
UPDATE "image_types" SET width = 1920, height = 1080 WHERE name = 'Background Image';