// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type EvaluationType string

const (
	EvaluationTypeSelf EvaluationType = "self"
	EvaluationTypeDm   EvaluationType = "dm"
)

func (e *EvaluationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EvaluationType(s)
	case string:
		*e = EvaluationType(s)
	default:
		return fmt.Errorf("unsupported scan type for EvaluationType: %T", src)
	}
	return nil
}

type NullEvaluationType struct {
	EvaluationType EvaluationType
	Valid          bool // Valid is true if EvaluationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEvaluationType) Scan(value interface{}) error {
	if value == nil {
		ns.EvaluationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EvaluationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEvaluationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EvaluationType), nil
}

type ImageVariant string

const (
	ImageVariant100x100  ImageVariant = "100x100"
	ImageVariant1200x800 ImageVariant = "1200x800"
	ImageVariant150x150  ImageVariant = "150x150"
	ImageVariant1920x200 ImageVariant = "1920x200"
	ImageVariant200x200  ImageVariant = "200x200"
	ImageVariant300x300  ImageVariant = "300x300"
	ImageVariant30x30    ImageVariant = "30x30"
	ImageVariantPublic   ImageVariant = "public"
)

func (e *ImageVariant) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImageVariant(s)
	case string:
		*e = ImageVariant(s)
	default:
		return fmt.Errorf("unsupported scan type for ImageVariant: %T", src)
	}
	return nil
}

type NullImageVariant struct {
	ImageVariant ImageVariant
	Valid        bool // Valid is true if ImageVariant is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImageVariant) Scan(value interface{}) error {
	if value == nil {
		ns.ImageVariant, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImageVariant.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImageVariant) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImageVariant), nil
}

type Character struct {
	ID             int32         `json:"id"`
	UserID         int32         `json:"user_id"`
	WorldID        int32         `json:"world_id"`
	RaceID         int32         `json:"race_id"`
	ImgID          sql.NullInt32 `json:"img_id"`
	Name           string        `json:"name"`
	Level          int32         `json:"level"`
	Experience     int32         `json:"experience"`
	SkillPoints    int32         `json:"skill_points"`
	PropertyPoints int32         `json:"property_points"`
	CreatedAt      time.Time     `json:"created_at"`
}

type CharacterProperty struct {
	CharacterID int32 `json:"character_id"`
	PropertyID  int32 `json:"property_id"`
	Value       int32 `json:"value"`
}

type CharacterSkill struct {
	CharacterID int32 `json:"character_id"`
	SkillID     int32 `json:"skill_id"`
	SkillLevel  int32 `json:"skill_level"`
}

type Chat struct {
	ID        int64     `json:"id"`
	UserID    int32     `json:"user_id"`
	Text      string    `json:"text"`
	CreatedAt time.Time `json:"created_at"`
}

type Evaluation struct {
	ID             int32          `json:"id"`
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	EvaluationType EvaluationType `json:"evaluation_type"`
}

type EvaluationVote struct {
	EvaluationID int32     `json:"evaluation_id"`
	UserID       int32     `json:"user_id"`
	UserIDVoter  int32     `json:"user_id_voter"`
	Value        float64   `json:"value"`
	CreatedAt    time.Time `json:"created_at"`
}

type Image struct {
	ID          int32          `json:"id"`
	ImageTypeID sql.NullInt32  `json:"image_type_id"`
	Name        sql.NullString `json:"name"`
	Url         string         `json:"url"`
	CreatedAt   time.Time      `json:"created_at"`
	BaseUrl     string         `json:"base_url"`
	ImgGuid     uuid.NullUUID  `json:"img_guid"`
	UserID      int32          `json:"user_id"`
}

type ImageType struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	// Variant name from cloudflare.
	Variant ImageVariant `json:"variant"`
}

type Property struct {
	ID      int32  `json:"id"`
	WorldID int32  `json:"world_id"`
	Name    string `json:"name"`
}

type Race struct {
	ID         int32         `json:"id"`
	WorldID    int32         `json:"world_id"`
	Name       string        `json:"name"`
	ImgID      sql.NullInt32 `json:"img_id"`
	IsPlayable bool          `json:"is_playable"`
}

type RaceProperty struct {
	RaceID     int32 `json:"race_id"`
	PropertyID int32 `json:"property_id"`
	MinValue   int32 `json:"min_value"`
	MaxValue   int32 `json:"max_value"`
}

type Role struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       int32     `json:"user_id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiredAt    time.Time `json:"expired_at"`
}

type Skill struct {
	ID       int32         `json:"id"`
	WorldID  int32         `json:"world_id"`
	ImgID    sql.NullInt32 `json:"img_id"`
	Name     string        `json:"name"`
	MaxLevel int32         `json:"max_level"`
}

type SkillRequirement struct {
	ID      int32         `json:"id"`
	SkillID int32         `json:"skill_id"`
	Level   sql.NullInt32 `json:"level"`
	RaceID  sql.NullInt32 `json:"race_id"`
}

type SkillRequirementProperty struct {
	SkillRequirementID int32 `json:"skill_requirement_id"`
	PropertyID         int32 `json:"property_id"`
	Value              int32 `json:"value"`
}

type SkillRequirementSkill struct {
	SkillRequirementID int32 `json:"skill_requirement_id"`
	SkillID            int32 `json:"skill_id"`
	Level              int32 `json:"level"`
}

type User struct {
	ID                int32         `json:"id"`
	Username          string        `json:"username"`
	HashedPassword    string        `json:"hashed_password"`
	Email             string        `json:"email"`
	ImgID             sql.NullInt32 `json:"img_id"`
	PasswordChangedAt time.Time     `json:"password_changed_at"`
	CreatedAt         time.Time     `json:"created_at"`
	IsEmailVerified   bool          `json:"is_email_verified"`
}

type UserPasswordReset struct {
	UserID    int32     `json:"user_id"`
	Code      string    `json:"code"`
	ExpiredAt time.Time `json:"expired_at"`
}

type UserRole struct {
	UserID    int32     `json:"user_id"`
	RoleID    int32     `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
}

type VerifyEmail struct {
	ID         int64     `json:"id"`
	UserID     int32     `json:"user_id"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}

type ViewWorld struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Public      bool           `json:"public"`
	CreatedAt   time.Time      `json:"created_at"`
	Description string         `json:"description"`
	ImageAvatar sql.NullString `json:"image_avatar"`
	ImageHeader sql.NullString `json:"image_header"`
	Rating      int32          `json:"rating"`
	Activity    int32          `json:"activity"`
}

type World struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Public      bool      `json:"public"`
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
}

type WorldAdmin struct {
	WorldID   sql.NullInt32 `json:"world_id"`
	UserID    sql.NullInt32 `json:"user_id"`
	CreatedAt time.Time     `json:"created_at"`
	IsMain    bool          `json:"is_main"`
}

type WorldImage struct {
	WorldID     int32         `json:"world_id"`
	ImageHeader sql.NullInt32 `json:"image_header"`
	ImageAvatar sql.NullInt32 `json:"image_avatar"`
}

type WorldStat struct {
	WorldID            int32 `json:"world_id"`
	FinalContentRating int32 `json:"final_content_rating"`
	FinalActivity      int32 `json:"final_activity"`
}

type WorldStatsHistory struct {
	WorldID            sql.NullInt32 `json:"world_id"`
	FinalContentRating int32         `json:"final_content_rating"`
	FinalActivity      int32         `json:"final_activity"`
	CreatedAt          time.Time     `json:"created_at"`
}
