// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: world.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createWorld = `-- name: CreateWorld :one
INSERT INTO worlds (
    name,
    description
) VALUES (
     $1, $2
 ) RETURNING id, name, public, created_at, description
`

type CreateWorldParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateWorld(ctx context.Context, arg CreateWorldParams) (World, error) {
	row := q.db.QueryRowContext(ctx, createWorld, arg.Name, arg.Description)
	var i World
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Public,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}

const createWorldAdmin = `-- name: CreateWorldAdmin :one
INSERT INTO world_admins (
    world_id,
    user_id,
    is_main
) VALUES ($1, $2, $3) RETURNING world_id, user_id, created_at, is_main
`

type CreateWorldAdminParams struct {
	WorldID sql.NullInt32 `json:"world_id"`
	UserID  sql.NullInt32 `json:"user_id"`
	IsMain  bool          `json:"is_main"`
}

func (q *Queries) CreateWorldAdmin(ctx context.Context, arg CreateWorldAdminParams) (WorldAdmin, error) {
	row := q.db.QueryRowContext(ctx, createWorldAdmin, arg.WorldID, arg.UserID, arg.IsMain)
	var i WorldAdmin
	err := row.Scan(
		&i.WorldID,
		&i.UserID,
		&i.CreatedAt,
		&i.IsMain,
	)
	return i, err
}

const deleteWorld = `-- name: DeleteWorld :exec
DELETE FROM worlds WHERE id = $1
`

func (q *Queries) DeleteWorld(ctx context.Context, worldID int32) error {
	_, err := q.db.ExecContext(ctx, deleteWorld, worldID)
	return err
}

const getAdminsOfWorld = `-- name: GetAdminsOfWorld :many
SELECT
    vu.id, vu.username, vu.hashed_password, vu.email, vu.img_id, vu.password_changed_at, vu.created_at, vu.is_email_verified, vu.image_avatar,
    wa.is_main as is_main
FROM
    view_users vu
    JOIN world_admins wa on wa.user_id = vu.id
WHERE
    wa.world_id = $1
`

type GetAdminsOfWorldRow struct {
	ID                int32          `json:"id"`
	Username          string         `json:"username"`
	HashedPassword    string         `json:"hashed_password"`
	Email             string         `json:"email"`
	ImgID             sql.NullInt32  `json:"img_id"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	CreatedAt         time.Time      `json:"created_at"`
	IsEmailVerified   bool           `json:"is_email_verified"`
	ImageAvatar       sql.NullString `json:"image_avatar"`
	IsMain            bool           `json:"is_main"`
}

func (q *Queries) GetAdminsOfWorld(ctx context.Context, worldID sql.NullInt32) ([]GetAdminsOfWorldRow, error) {
	rows, err := q.db.QueryContext(ctx, getAdminsOfWorld, worldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminsOfWorldRow{}
	for rows.Next() {
		var i GetAdminsOfWorldRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.HashedPassword,
			&i.Email,
			&i.ImgID,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.IsEmailVerified,
			&i.ImageAvatar,
			&i.IsMain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorldByID = `-- name: GetWorldByID :one
SELECT id, name, public, created_at, description, image_avatar, image_header, rating, activity FROM view_worlds WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorldByID(ctx context.Context, worldID int32) (ViewWorld, error) {
	row := q.db.QueryRowContext(ctx, getWorldByID, worldID)
	var i ViewWorld
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Public,
		&i.CreatedAt,
		&i.Description,
		&i.ImageAvatar,
		&i.ImageHeader,
		&i.Rating,
		&i.Activity,
	)
	return i, err
}

const getWorlds = `-- name: GetWorlds :many
SELECT id, name, public, created_at, description, image_avatar, image_header, rating, activity FROM view_worlds
WHERE ($1::boolean IS NULL OR public = $1)
ORDER BY
    CASE
     WHEN $2::bool
         THEN $3::VARCHAR
     ELSE 'activity'
     END
DESC
LIMIT $5
OFFSET $4
`

type GetWorldsParams struct {
	IsPublic    bool   `json:"is_public"`
	OrderResult bool   `json:"order_result"`
	OrderBy     string `json:"order_by"`
	PageOffset  int32  `json:"page_offset"`
	PageLimit   int32  `json:"page_limit"`
}

func (q *Queries) GetWorlds(ctx context.Context, arg GetWorldsParams) ([]ViewWorld, error) {
	rows, err := q.db.QueryContext(ctx, getWorlds,
		arg.IsPublic,
		arg.OrderResult,
		arg.OrderBy,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViewWorld{}
	for rows.Next() {
		var i ViewWorld
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Public,
			&i.CreatedAt,
			&i.Description,
			&i.ImageAvatar,
			&i.ImageHeader,
			&i.Rating,
			&i.Activity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorldsOfUser = `-- name: GetWorldsOfUser :many
SELECT
    vw.id, vw.name, vw.public, vw.created_at, vw.description, vw.image_avatar, vw.image_header, vw.rating, vw.activity
FROM
    view_worlds vw
    JOIN world_admins wa ON wa.world_id = vw.id
WHERE
    wa.user_id = $1
`

func (q *Queries) GetWorldsOfUser(ctx context.Context, userID sql.NullInt32) ([]ViewWorld, error) {
	rows, err := q.db.QueryContext(ctx, getWorldsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViewWorld{}
	for rows.Next() {
		var i ViewWorld
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Public,
			&i.CreatedAt,
			&i.Description,
			&i.ImageAvatar,
			&i.ImageHeader,
			&i.Rating,
			&i.Activity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isWorldAdmin = `-- name: IsWorldAdmin :one
SELECT world_id, user_id, created_at, is_main FROM world_admins WHERE user_id = $1 AND world_id = $2
`

type IsWorldAdminParams struct {
	UserID  sql.NullInt32 `json:"user_id"`
	WorldID sql.NullInt32 `json:"world_id"`
}

func (q *Queries) IsWorldAdmin(ctx context.Context, arg IsWorldAdminParams) (WorldAdmin, error) {
	row := q.db.QueryRowContext(ctx, isWorldAdmin, arg.UserID, arg.WorldID)
	var i WorldAdmin
	err := row.Scan(
		&i.WorldID,
		&i.UserID,
		&i.CreatedAt,
		&i.IsMain,
	)
	return i, err
}

const updateWorld = `-- name: UpdateWorld :one
UPDATE worlds
SET
    name = COALESCE($1, name),
    public = COALESCE($2, public),
    description = COALESCE($3, description)
WHERE
    id = $4
RETURNING id, name, public, created_at, description
`

type UpdateWorldParams struct {
	Name        sql.NullString `json:"name"`
	Public      sql.NullBool   `json:"public"`
	Description sql.NullString `json:"description"`
	WorldID     int32          `json:"world_id"`
}

func (q *Queries) UpdateWorld(ctx context.Context, arg UpdateWorldParams) (World, error) {
	row := q.db.QueryRowContext(ctx, updateWorld,
		arg.Name,
		arg.Public,
		arg.Description,
		arg.WorldID,
	)
	var i World
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Public,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}
