// Use DBML to define your database structure
// Docs: https://www.dbml.org/docs

enum image_variant {
  100x100
  1200x800
  150x150
  1920x300
  200x200
  300x300
  30x30
  original
  public
  600x400
  400x600
  300x200
  200x300
  250x50
}

enum pin_shape {
  square
  triangle
  pin
  circle
  hexagon
  octagon
  star
  diamond
  pentagon
  heart
  cloud
}

enum entity_type {
  unknown
  post
  map
  location
  character
  image
}

Table image_types {
  id int [not null, unique]
  name varchar [unique, not null]
  description text [not null]
  variant image_variant [not null, note: 'Variant name from cloudflare. ']
}

Table images {
  id int [pk, increment]
  user_id int [not null, ref: > users.id]
  img_guid uuid [unique]
  image_type_id int [ref: > image_types.id]
  name varchar [unique]
  url varchar [not null]
  base_url varchar [not null]
  created_at timestamptz [not null, default: `now()`]
  width int [not null, default: 0]
  height int [not null, default: 0]
}

Table users {
  id int [pk, increment]
  username varchar [not null, unique]
  hashed_password varchar [not null]
  email varchar [not null, unique]
  img_id int [null, ref: > images.id]
  password_changed_at timestamptz [not null, default: '0001-01-01 00:00:00Z']
  created_at timestamptz [not null, default: `now()`]
  is_email_verified bool [not null, default: false]
  introduction_post_id int [null, ref: > posts.id]
}

Table sessions {
  id uuid [pk]
  user_id int [not null, ref: > users.id]
  username varchar [not null]
  refresh_token varchar [not null]
  user_agent varchar [not null]
  client_ip varchar [not null]
  is_blocked boolean [not null, default: false]
  created_at timestamptz [not null, default: `now()`]
  expired_at timestamptz [not null, default: `now() + INTERVAL '15 minutes'`]
}

enum evaluation_type {
  self
  dm
}

Table evaluations {
  id int [pk, increment]
  name varchar [not null]
  description varchar [not null]
  evaluation_type evaluation_type [not null]
}

Table evaluation_votes {
  evaluation_id int [not null, ref: > evaluations.id]
  user_id int [not null, ref: > users.id]
  user_id_voter int [not null, ref: > users.id]
  value float [not null]
  created_at timestamptz [not null, default: `now()`]

  indexes {
    (evaluation_id, user_id, user_id_voter) [unique]
  }
}

Table user_password_reset {
  user_id int [not null, ref: > users.id]
  code varchar [not null]
  expired_at timestamptz [not null, default: `now() + INTERVAL '15 minutes'`]
}

Table verify_emails {
  id bigserial [pk]
  user_id int [not null, ref: > users.id]
  email varchar [not null]
  secret_code varchar [not null]
  is_used boolean [not null, default: false]
  created_at timestamptz [not null, default: `now()`]
  expired_at timestamptz [not null, default: `now() + INTERVAL '15 minutes'`]
}

Table roles {
  id int [not null, unique]
  name varchar [not null, unique]
  description text [not null]
}

Table user_roles {
  user_id int [not null, ref: > users.id]
  role_id int [not null, ref: > roles.id]
  created_at timestamptz [not null, default: `now()`]

  indexes {
    (role_id, user_id) [unique]
  }
}

Table chat {
  id bigserial [pk]
  user_id int [not null, ref: > users.id]
  text varchar [not null]
  created_at timestamp [not null, default: `now()`]
}

Table worlds {
  id int [pk, increment]
  name varchar [not null, unique]
  based_on varchar [not null]
  public boolean [not null, default: false]
  created_at timestamptz [not null, default: `now()`]
  short_description varchar [not null, default: '']
  description_post_id int [null, ref: > posts.id]
}

Table world_admins {
  world_id int [not null, ref: > worlds.id]
  user_id int [not null, ref: > users.id]
  created_at timestamptz [not null, default: `now()`]
  super_admin boolean [not null, default: false]
  approved int [not null, note: '0 = NO, 1 = YES, 2 = PENDING']
  motivational_letter varchar [not null]

  indexes {
    (world_id, user_id) [unique]
  }
}

Table world_menu {
  world_id int [not null, ref: > worlds.id]
  menu_id int [not null, ref: > menus.id]

  indexes {
    (world_id, menu_id) [unique]
  }
}

Table world_tags_available {
  id int [pk, increment]
  tag varchar [not null, unique]
}

Table world_tags {
  world_id int [not null, ref: > worlds.id]
  tag_id int [not null]

  indexes {
    (world_id, tag_id) [unique]
  }
}

Ref: world_tags.tag_id > world_tags_available.id [delete: cascade]

Table world_images {
  world_id int [pk, ref: > worlds.id]
  header_img_id int [ref: > images.id]
  thumbnail_img_id int [ref: > images.id]
  avatar_img_id int [ref: > images.id]
}

Table world_activity {
  world_id int [not null, ref: > worlds.id]
  date date [not null]
  post_count int [not null]
  quest_count int [not null]
  resource_count int [not null]

  indexes {
    (world_id, date) [unique]
  }
}

Table races {
  id int [pk, increment]
  world_id int [not null, ref: > worlds.id]
  name varchar [not null]
  img_id int [ref: > images.id]
  is_playable boolean [not null, default: true]

  indexes {
    (world_id, name) [unique]
  }
}

Table properties {
  id int [pk, increment]
  world_id int [not null, ref: > worlds.id]
  name varchar [not null]

  indexes {
    (world_id, name) [unique]
  }
}

Table race_properties {
  race_id int [not null, ref: > races.id]
  property_id int [not null, ref: > properties.id]
  min_value int [not null]
  max_value int [not null]

  indexes {
    (race_id, property_id) [unique]
  }
}

Table characters {
  id int [pk, increment]
  user_id int [not null, ref: > users.id]
  world_id int [not null, ref: > worlds.id]
  race_id int [not null, ref: > races.id]
  img_id int [ref: > images.id]
  name varchar [not null]
  level int [not null]
  experience int [not null]
  skill_points int [not null]
  property_points int [not null]
  created_at timestamptz [not null, default: `now()`]

  indexes {
    (world_id, name) [unique]
  }
}


Table character_properties {
  character_id int [not null, ref: > characters.id]
  property_id int [not null, ref: > properties.id]
  value int [not null]

  indexes {
    (character_id, property_id) [unique]
  }
}

Table skills {
  id int [pk, increment]
  world_id int [not null, ref: > worlds.id]
  img_id int [ref: > images.id]
  name varchar [not null]
  max_level int [not null]
}

Table skill_requirements {
  id int [primary key]
  skill_id int [not null, ref: > skills.id]
  level int [null]
  race_id int [null, ref: > races.id]
}

Table skill_requirement_skills {
  skill_requirement_id int [not null, ref: > skill_requirements.id]
  skill_id int [not null, ref: > skills.id]
  level int [not null]
}

Table skill_requirement_properties {
  skill_requirement_id int [not null, ref: > skill_requirements.id]
  property_id int [not null, ref: > properties.id]
  value int [not null]
}

Table character_skills {
  character_id int [not null, ref: > characters.id]
  skill_id int [not null, ref: > skills.id]
  skill_level int [not null]
}

Table posts {
  id int [pk, increment]
  post_type_id int [not null, ref: > post_types.id]
  user_id int [not null, ref: > users.id]
  title varchar [not null]
  description varchar
  content varchar [not null]
  created_at timestamptz [not null, default: `now()`]
  deleted_at timestamptz
  last_updated_at timestamptz
  last_updated_user_id int [ref: > users.id]
  is_draft bool [not null]
  is_private bool [not null]
  thumbnail_img_id int [ref: > images.id]
}

Table post_types {
  id int [pk]
  name varchar [not null]
  draftable bool [not null, default: true]
  privatable bool [not null, default: false]
}

Table post_history {
  id int [pk, increment]
  post_id int [not null, ref: > posts.id]
  post_type_id int [not null, ref: > post_types.id]
  user_id int [not null, ref: > users.id]
  title varchar [not null]
  description varchar
  content varchar [not null]
  created_at timestamptz [not null, default: `now()`]
  deleted_at timestamptz
  last_updated_at timestamptz
  last_updated_user_id int [ref: > users.id]
  is_draft bool [not null]
  is_private bool [not null]
  thumbnail_img_id int [ref: > images.id]
}

Table menus {
  id int [pk, increment]
  menu_code varchar [not null, unique]
  menu_header_img_id int [null, ref: > images.id]
}

Table menu_items {
  id int [pk, increment]
  menu_id int [not null, ref: > menus.id]
  menu_item_code varchar [not null]
  name varchar [not null]
  position int [not null]
  is_main bool [not null, default: false]
  description_post_id int [null, ref: > posts.id]
  entity_group_id int [null, ref: > entity_groups.id]
}

Table menu_item_posts {
  menu_id int [not null, ref: > menus.id]
  menu_item_id int [ref: > menu_items.id]
  post_id int [not null, ref: > posts.id]
  position int [not null]

  indexes {
    (menu_item_id, post_id) [unique]
  }
}

Table maps {
  id int [pk, increment]
  name varchar [not null]
  type varchar
  description varchar
  width int [not null]
  height int [not null]
  thumbnail_image_id int [ref: > images.id]
}

Table locations {
  id int [pk, increment]
  name varchar [not null]
  description varchar
  post_id int [ref: > posts.id]
  thumbnail_image_id int [ref: > images.id]
}

Table map_layers {
  id int [pk, increment]
  name varchar [not null]
  map_id int [not null, ref: > maps.id]
  image_id int [not null, ref: > images.id]
  is_main bool [not null, default: false]
  enabled bool [not null, default: true]
  sublayer bool [not null, default: false]
}

Table map_pins {
  id int [pk, increment]
  name varchar [not null]
  map_id int [not null, ref: > maps.id]
  map_pin_type_id int [ref: > map_pin_types.id]
  location_id int [ref: > locations.id]
  map_layer_id int [ref: > map_layers.id]
  x int [not null]
  y int [not null]
}

Table map_pin_type_group {
  id int [pk, increment]
  name varchar [not null]
}

Table world_map_pin_type_groups {
  world_id int [not null, ref: > worlds.id]
  map_pin_type_group_id int [not null, ref: > map_pin_type_group.id]

  indexes {
    (world_id, map_pin_type_group_id) [unique]
  }
}

Table map_pin_types {
  id int [pk, increment]
  map_pin_type_group_id int [not null, ref: > map_pin_type_group.id]
  shape pin_shape [not null, default: "pin"]
  background_color varchar
  border_color varchar
  icon_color varchar
  icon varchar
  icon_size int
  width int
  section varchar [not null, default: "base"]
}

Table world_maps {
  world_id int [not null, ref: > worlds.id]
  map_id int [not null, ref: > maps.id]

  indexes {
    (world_id, map_id) [unique]
  }
}

Table world_locations {
  world_id int [not null, ref: > worlds.id]
  location_id int [not null, ref: > locations.id]

  indexes {
    (world_id, location_id) [unique]
  }
}

Table world_posts {
  world_id int [not null, ref: > worlds.id]
  post_id int [not null, ref: > posts.id]

  indexes {
    (world_id, post_id) [unique]
  }
}

Table quests {
  id int [pk, increment]
}

Table systems {
  id int [pk, increment]
}

Table modules {
  id int [pk, increment]
  world_id int [ref: > worlds.id]
  system_id int [ref: > systems.id]
  character_id int [ref: > characters.id]
  quest_id int [ref: > quests.id]
}

Table module_tags_available {
  id int [pk, increment]
  module_id int [not null, ref: > modules.id]
  tag varchar [not null, unique]
}

Table asset_tags {
  asset_id int [not null, ref: > entities.id]
  tag_id int [not null, ref: > module_tags_available.id]

  indexes {
    (asset_id, tag_id) [unique]
  }
}

Table entities {
  id int [pk, increment]
  module_id int [not null, ref: > modules.id]
  type entity_type [not null]
  post_id int [ref: > posts.id]
  map_id int [ref: > maps.id]
  location_id int [ref: > locations.id]
  image_id int [ref: > images.id]
}

Table entity_groups {
  id int [pk, increment]
  name varchar
  description varchar
  style varchar [default: "framed"]
  direction varchar [default: "vertical"]
}

Table entity_group_content {
  id int [pk, increment]
  entity_group_id int [not null, ref: > entity_groups.id]
  position int [not null]
  content_entity_id int [ref: > entities.id]
  content_entity_group_id int [ref: > entity_groups.id]
}

TableGroup Evaluations {
  evaluations
  evaluation_votes
}

TableGroup Images {
  image_types
  images
}

TableGroup UserStuff {
  users
  user_roles
  roles
  verify_emails
  sessions
  user_password_reset
}

TableGroup Worlds {
  worlds
  world_images
  world_activity
  world_admins
  world_tags_available
  world_tags
  world_menu
}

TableGroup Posts {
  posts
  post_types
  post_history
}

TableGroup Menus {
  menus
  menu_items
  menu_item_posts
}

TableGroup Entities {
  entities
  entity_groups
  entity_group_content
}


//Ref: users.id < follows.following_user_id

//Ref: users.id < follows.followed_user_id
