// Use DBML to define your database structure
// Docs: https://www.dbml.org/docs


Table users {
  id integer [primary key]
  username varchar [not null, unique]
  email varchar [not null]
  avatar varchar
  created_at timestamp [default: `now()`]
}

Table roles {
  id integer [primary key]
  name varchar [not null, unique]
}

Table user_roles {
  user_id integer [not null]
  role_id integer [not null]
}

Table chat {
  id integer [primary key]
  user_id integer [not null]
  text varchar [not null]
  created_at timestamp [default: `now()`]
}

Ref: chat.user_id > users.id // many-to-one
Ref: user_roles.user_id > users.id
Ref: user_roles.role_id > roles.id

//Ref: users.id < follows.following_user_id

//Ref: users.id < follows.followed_user_id
