// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: services/posts/rpc_post_history.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPostHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId int32 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
}

func (x *GetPostHistoryRequest) Reset() {
	*x = GetPostHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_posts_rpc_post_history_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPostHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostHistoryRequest) ProtoMessage() {}

func (x *GetPostHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_posts_rpc_post_history_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPostHistoryRequest) Descriptor() ([]byte, []int) {
	return file_services_posts_rpc_post_history_proto_rawDescGZIP(), []int{0}
}

func (x *GetPostHistoryRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetPostHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HistoryPosts []*HistoryPost `protobuf:"bytes,1,rep,name=historyPosts,proto3" json:"historyPosts,omitempty"`
}

func (x *GetPostHistoryResponse) Reset() {
	*x = GetPostHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_posts_rpc_post_history_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPostHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostHistoryResponse) ProtoMessage() {}

func (x *GetPostHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_posts_rpc_post_history_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetPostHistoryResponse) Descriptor() ([]byte, []int) {
	return file_services_posts_rpc_post_history_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostHistoryResponse) GetHistoryPosts() []*HistoryPost {
	if x != nil {
		return x.HistoryPosts
	}
	return nil
}

type GetPostHistoryByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId        int32 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	PostHistoryId int32 `protobuf:"varint,2,opt,name=postHistoryId,proto3" json:"postHistoryId,omitempty"`
}

func (x *GetPostHistoryByIdRequest) Reset() {
	*x = GetPostHistoryByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_posts_rpc_post_history_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPostHistoryByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostHistoryByIdRequest) ProtoMessage() {}

func (x *GetPostHistoryByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_posts_rpc_post_history_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostHistoryByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPostHistoryByIdRequest) Descriptor() ([]byte, []int) {
	return file_services_posts_rpc_post_history_proto_rawDescGZIP(), []int{2}
}

func (x *GetPostHistoryByIdRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetPostHistoryByIdRequest) GetPostHistoryId() int32 {
	if x != nil {
		return x.PostHistoryId
	}
	return 0
}

var File_services_posts_rpc_post_history_proto protoreflect.FileDescriptor

var file_services_posts_rpc_post_history_proto_rawDesc = []byte{
	0x0a, 0x25, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x73,
	0x2f, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x19, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x2f, 0x70, 0x6f, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73,
	0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x6f,
	0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x0c, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x0c, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x59, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x73,
	0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x70,
	0x6f, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x70, 0x6f, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x49,
	0x64, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x68, 0x65, 0x2d, 0x6d, 0x65, 0x64, 0x6f, 0x2f, 0x74, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x75,
	0x6e, 0x64, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_posts_rpc_post_history_proto_rawDescOnce sync.Once
	file_services_posts_rpc_post_history_proto_rawDescData = file_services_posts_rpc_post_history_proto_rawDesc
)

func file_services_posts_rpc_post_history_proto_rawDescGZIP() []byte {
	file_services_posts_rpc_post_history_proto_rawDescOnce.Do(func() {
		file_services_posts_rpc_post_history_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_posts_rpc_post_history_proto_rawDescData)
	})
	return file_services_posts_rpc_post_history_proto_rawDescData
}

var file_services_posts_rpc_post_history_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_posts_rpc_post_history_proto_goTypes = []interface{}{
	(*GetPostHistoryRequest)(nil),     // 0: pb.GetPostHistoryRequest
	(*GetPostHistoryResponse)(nil),    // 1: pb.GetPostHistoryResponse
	(*GetPostHistoryByIdRequest)(nil), // 2: pb.GetPostHistoryByIdRequest
	(*HistoryPost)(nil),               // 3: pb.HistoryPost
}
var file_services_posts_rpc_post_history_proto_depIdxs = []int32{
	3, // 0: pb.GetPostHistoryResponse.historyPosts:type_name -> pb.HistoryPost
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_posts_rpc_post_history_proto_init() }
func file_services_posts_rpc_post_history_proto_init() {
	if File_services_posts_rpc_post_history_proto != nil {
		return
	}
	file_services_posts_post_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_services_posts_rpc_post_history_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPostHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_posts_rpc_post_history_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPostHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_posts_rpc_post_history_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPostHistoryByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_posts_rpc_post_history_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_posts_rpc_post_history_proto_goTypes,
		DependencyIndexes: file_services_posts_rpc_post_history_proto_depIdxs,
		MessageInfos:      file_services_posts_rpc_post_history_proto_msgTypes,
	}.Build()
	File_services_posts_rpc_post_history_proto = out.File
	file_services_posts_rpc_post_history_proto_rawDesc = nil
	file_services_posts_rpc_post_history_proto_goTypes = nil
	file_services_posts_rpc_post_history_proto_depIdxs = nil
}
