// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.0
// source: services/worlds/rpc_world.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWorldRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ShortDescription string `protobuf:"bytes,2,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	BasedOn          string `protobuf:"bytes,3,opt,name=basedOn,proto3" json:"basedOn,omitempty"`
}

func (x *CreateWorldRequest) Reset() {
	*x = CreateWorldRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_worlds_rpc_world_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorldRequest) ProtoMessage() {}

func (x *CreateWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_worlds_rpc_world_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorldRequest.ProtoReflect.Descriptor instead.
func (*CreateWorldRequest) Descriptor() ([]byte, []int) {
	return file_services_worlds_rpc_world_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWorldRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorldRequest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *CreateWorldRequest) GetBasedOn() string {
	if x != nil {
		return x.BasedOn
	}
	return ""
}

type CreateWorldResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	World  *World      `protobuf:"bytes,1,opt,name=world,proto3" json:"world,omitempty"`
	Module *ViewModule `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
}

func (x *CreateWorldResponse) Reset() {
	*x = CreateWorldResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_worlds_rpc_world_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorldResponse) ProtoMessage() {}

func (x *CreateWorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_worlds_rpc_world_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorldResponse.ProtoReflect.Descriptor instead.
func (*CreateWorldResponse) Descriptor() ([]byte, []int) {
	return file_services_worlds_rpc_world_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorldResponse) GetWorld() *World {
	if x != nil {
		return x.World
	}
	return nil
}

func (x *CreateWorldResponse) GetModule() *ViewModule {
	if x != nil {
		return x.Module
	}
	return nil
}

type UpdateWorldRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorldId           int32   `protobuf:"varint,1,opt,name=worldId,proto3" json:"worldId,omitempty"`
	Name              *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	ShortDescription  *string `protobuf:"bytes,3,opt,name=shortDescription,proto3,oneof" json:"shortDescription,omitempty"`
	Public            *bool   `protobuf:"varint,4,opt,name=public,proto3,oneof" json:"public,omitempty"`
	BasedOn           *string `protobuf:"bytes,5,opt,name=basedOn,proto3,oneof" json:"basedOn,omitempty"`
	DescriptionPostId *int32  `protobuf:"varint,6,opt,name=descriptionPostId,proto3,oneof" json:"descriptionPostId,omitempty"`
}

func (x *UpdateWorldRequest) Reset() {
	*x = UpdateWorldRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_worlds_rpc_world_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorldRequest) ProtoMessage() {}

func (x *UpdateWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_worlds_rpc_world_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorldRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorldRequest) Descriptor() ([]byte, []int) {
	return file_services_worlds_rpc_world_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateWorldRequest) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *UpdateWorldRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateWorldRequest) GetShortDescription() string {
	if x != nil && x.ShortDescription != nil {
		return *x.ShortDescription
	}
	return ""
}

func (x *UpdateWorldRequest) GetPublic() bool {
	if x != nil && x.Public != nil {
		return *x.Public
	}
	return false
}

func (x *UpdateWorldRequest) GetBasedOn() string {
	if x != nil && x.BasedOn != nil {
		return *x.BasedOn
	}
	return ""
}

func (x *UpdateWorldRequest) GetDescriptionPostId() int32 {
	if x != nil && x.DescriptionPostId != nil {
		return *x.DescriptionPostId
	}
	return 0
}

type UploadWorldImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorldId     int32  `protobuf:"varint,1,opt,name=worldId,proto3" json:"worldId,omitempty"`
	Data        []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ImageTypeId int32  `protobuf:"varint,3,opt,name=imageTypeId,proto3" json:"imageTypeId,omitempty"`
}

func (x *UploadWorldImageRequest) Reset() {
	*x = UploadWorldImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_worlds_rpc_world_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadWorldImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadWorldImageRequest) ProtoMessage() {}

func (x *UploadWorldImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_worlds_rpc_world_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadWorldImageRequest.ProtoReflect.Descriptor instead.
func (*UploadWorldImageRequest) Descriptor() ([]byte, []int) {
	return file_services_worlds_rpc_world_proto_rawDescGZIP(), []int{3}
}

func (x *UploadWorldImageRequest) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *UploadWorldImageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadWorldImageRequest) GetImageTypeId() int32 {
	if x != nil {
		return x.ImageTypeId
	}
	return 0
}

type TagUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagId int32 `protobuf:"varint,1,opt,name=tagId,proto3" json:"tagId,omitempty"`
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *TagUsage) Reset() {
	*x = TagUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_worlds_rpc_world_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagUsage) ProtoMessage() {}

func (x *TagUsage) ProtoReflect() protoreflect.Message {
	mi := &file_services_worlds_rpc_world_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagUsage.ProtoReflect.Descriptor instead.
func (*TagUsage) Descriptor() ([]byte, []int) {
	return file_services_worlds_rpc_world_proto_rawDescGZIP(), []int{4}
}

func (x *TagUsage) GetTagId() int32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *TagUsage) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetWorldsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Public  *bool   `protobuf:"varint,1,opt,name=public,proto3,oneof" json:"public,omitempty"`
	Tags    []int32 `protobuf:"varint,2,rep,packed,name=tags,proto3" json:"tags,omitempty"`
	OrderBy *string `protobuf:"bytes,3,opt,name=orderBy,proto3,oneof" json:"orderBy,omitempty"`
	Limit   *int32  `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset  *int32  `protobuf:"varint,5,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
}

func (x *GetWorldsRequest) Reset() {
	*x = GetWorldsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_worlds_rpc_world_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorldsRequest) ProtoMessage() {}

func (x *GetWorldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_worlds_rpc_world_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorldsRequest.ProtoReflect.Descriptor instead.
func (*GetWorldsRequest) Descriptor() ([]byte, []int) {
	return file_services_worlds_rpc_world_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorldsRequest) GetPublic() bool {
	if x != nil && x.Public != nil {
		return *x.Public
	}
	return false
}

func (x *GetWorldsRequest) GetTags() []int32 {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetWorldsRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *GetWorldsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetWorldsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type GetWorldsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorldIds   []int32 `protobuf:"varint,1,rep,packed,name=worldIds,proto3" json:"worldIds,omitempty"`
	TotalCount int32   `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
}

func (x *GetWorldsResponse) Reset() {
	*x = GetWorldsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_worlds_rpc_world_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorldsResponse) ProtoMessage() {}

func (x *GetWorldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_worlds_rpc_world_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorldsResponse.ProtoReflect.Descriptor instead.
func (*GetWorldsResponse) Descriptor() ([]byte, []int) {
	return file_services_worlds_rpc_world_proto_rawDescGZIP(), []int{6}
}

func (x *GetWorldsResponse) GetWorldIds() []int32 {
	if x != nil {
		return x.WorldIds
	}
	return nil
}

func (x *GetWorldsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetWorldByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorldId int32 `protobuf:"varint,1,opt,name=worldId,proto3" json:"worldId,omitempty"`
}

func (x *GetWorldByIdRequest) Reset() {
	*x = GetWorldByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_worlds_rpc_world_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorldByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorldByIdRequest) ProtoMessage() {}

func (x *GetWorldByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_worlds_rpc_world_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorldByIdRequest.ProtoReflect.Descriptor instead.
func (*GetWorldByIdRequest) Descriptor() ([]byte, []int) {
	return file_services_worlds_rpc_world_proto_rawDescGZIP(), []int{7}
}

func (x *GetWorldByIdRequest) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

type UpdateWorldIntroductionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorldId int32  `protobuf:"varint,1,opt,name=worldId,proto3" json:"worldId,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *UpdateWorldIntroductionRequest) Reset() {
	*x = UpdateWorldIntroductionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_worlds_rpc_world_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWorldIntroductionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorldIntroductionRequest) ProtoMessage() {}

func (x *UpdateWorldIntroductionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_worlds_rpc_world_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorldIntroductionRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorldIntroductionRequest) Descriptor() ([]byte, []int) {
	return file_services_worlds_rpc_world_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateWorldIntroductionRequest) GetWorldId() int32 {
	if x != nil {
		return x.WorldId
	}
	return 0
}

func (x *UpdateWorldIntroductionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_services_worlds_rpc_world_proto protoreflect.FileDescriptor

var file_services_worlds_rpc_world_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x73, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x73, 0x2f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6e, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6c, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x73, 0x65, 0x64,
	0x4f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x73, 0x65, 0x64, 0x4f,
	0x6e, 0x22, 0x5e, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6c, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x6f, 0x72,
	0x6c, 0x64, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x56,
	0x69, 0x65, 0x77, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x22, 0xb2, 0x02, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6c,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x10, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x10, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x06,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x62, 0x61, 0x73,
	0x65, 0x64, 0x4f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x07, 0x62, 0x61,
	0x73, 0x65, 0x64, 0x4f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x11, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x04, 0x52, 0x11, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x64, 0x4f, 0x6e,
	0x42, 0x14, 0x0a, 0x12, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x69, 0x0a, 0x17, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x57, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x20, 0x0a, 0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x49,
	0x64, 0x22, 0x36, 0x0a, 0x08, 0x54, 0x61, 0x67, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x61,
	0x67, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xc6, 0x01, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00,
	0x52, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12,
	0x1d, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x88, 0x01, 0x01, 0x12, 0x19,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x02, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x22, 0x4f, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x49, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x2f, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x1e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f,
	0x72, 0x6c, 0x64, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x2d, 0x6d, 0x65, 0x64,
	0x6f, 0x2f, 0x74, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x2d, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_worlds_rpc_world_proto_rawDescOnce sync.Once
	file_services_worlds_rpc_world_proto_rawDescData = file_services_worlds_rpc_world_proto_rawDesc
)

func file_services_worlds_rpc_world_proto_rawDescGZIP() []byte {
	file_services_worlds_rpc_world_proto_rawDescOnce.Do(func() {
		file_services_worlds_rpc_world_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_worlds_rpc_world_proto_rawDescData)
	})
	return file_services_worlds_rpc_world_proto_rawDescData
}

var file_services_worlds_rpc_world_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_services_worlds_rpc_world_proto_goTypes = []interface{}{
	(*CreateWorldRequest)(nil),             // 0: pb.CreateWorldRequest
	(*CreateWorldResponse)(nil),            // 1: pb.CreateWorldResponse
	(*UpdateWorldRequest)(nil),             // 2: pb.UpdateWorldRequest
	(*UploadWorldImageRequest)(nil),        // 3: pb.UploadWorldImageRequest
	(*TagUsage)(nil),                       // 4: pb.TagUsage
	(*GetWorldsRequest)(nil),               // 5: pb.GetWorldsRequest
	(*GetWorldsResponse)(nil),              // 6: pb.GetWorldsResponse
	(*GetWorldByIdRequest)(nil),            // 7: pb.GetWorldByIdRequest
	(*UpdateWorldIntroductionRequest)(nil), // 8: pb.UpdateWorldIntroductionRequest
	(*World)(nil),                          // 9: pb.World
	(*ViewModule)(nil),                     // 10: pb.ViewModule
}
var file_services_worlds_rpc_world_proto_depIdxs = []int32{
	9,  // 0: pb.CreateWorldResponse.world:type_name -> pb.World
	10, // 1: pb.CreateWorldResponse.module:type_name -> pb.ViewModule
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_services_worlds_rpc_world_proto_init() }
func file_services_worlds_rpc_world_proto_init() {
	if File_services_worlds_rpc_world_proto != nil {
		return
	}
	file_services_worlds_world_proto_init()
	file_services_modules_module_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_services_worlds_rpc_world_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorldRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_worlds_rpc_world_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorldResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_worlds_rpc_world_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWorldRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_worlds_rpc_world_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadWorldImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_worlds_rpc_world_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_worlds_rpc_world_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorldsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_worlds_rpc_world_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorldsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_worlds_rpc_world_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorldByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_worlds_rpc_world_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWorldIntroductionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_services_worlds_rpc_world_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_services_worlds_rpc_world_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_worlds_rpc_world_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_worlds_rpc_world_proto_goTypes,
		DependencyIndexes: file_services_worlds_rpc_world_proto_depIdxs,
		MessageInfos:      file_services_worlds_rpc_world_proto_msgTypes,
	}.Build()
	File_services_worlds_rpc_world_proto = out.File
	file_services_worlds_rpc_world_proto_rawDesc = nil
	file_services_worlds_rpc_world_proto_goTypes = nil
	file_services_worlds_rpc_world_proto_depIdxs = nil
}
