// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.0
// source: services/menus/rpc_menu.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMenuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId      int32   `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	Code        *string `protobuf:"bytes,2,opt,name=code,proto3,oneof" json:"code,omitempty"`
	HeaderImgId *int32  `protobuf:"varint,3,opt,name=headerImgId,proto3,oneof" json:"headerImgId,omitempty"`
}

func (x *UpdateMenuRequest) Reset() {
	*x = UpdateMenuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuRequest) ProtoMessage() {}

func (x *UpdateMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuRequest) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMenuRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *UpdateMenuRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *UpdateMenuRequest) GetHeaderImgId() int32 {
	if x != nil && x.HeaderImgId != nil {
		return *x.HeaderImgId
	}
	return 0
}

type GetMenuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId int32 `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{1}
}

func (x *GetMenuRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

type CreateMenuItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId   int32  `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	Code     string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Position *int32 `protobuf:"varint,4,opt,name=position,proto3,oneof" json:"position,omitempty"`
	IsMain   *bool  `protobuf:"varint,5,opt,name=isMain,proto3,oneof" json:"isMain,omitempty"`
}

func (x *CreateMenuItemRequest) Reset() {
	*x = CreateMenuItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuItemRequest) ProtoMessage() {}

func (x *CreateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMenuItemRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *CreateMenuItemRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateMenuItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMenuItemRequest) GetPosition() int32 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *CreateMenuItemRequest) GetIsMain() bool {
	if x != nil && x.IsMain != nil {
		return *x.IsMain
	}
	return false
}

type UpdateMenuItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId            int32   `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	MenuItemId        int32   `protobuf:"varint,2,opt,name=menuItemId,proto3" json:"menuItemId,omitempty"`
	Code              *string `protobuf:"bytes,3,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Name              *string `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Position          *int32  `protobuf:"varint,5,opt,name=position,proto3,oneof" json:"position,omitempty"`
	IsMain            *bool   `protobuf:"varint,6,opt,name=isMain,proto3,oneof" json:"isMain,omitempty"`
	DescriptionPostId *int32  `protobuf:"varint,7,opt,name=descriptionPostId,proto3,oneof" json:"descriptionPostId,omitempty"`
}

func (x *UpdateMenuItemRequest) Reset() {
	*x = UpdateMenuItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemRequest) ProtoMessage() {}

func (x *UpdateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMenuItemRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *UpdateMenuItemRequest) GetMenuItemId() int32 {
	if x != nil {
		return x.MenuItemId
	}
	return 0
}

func (x *UpdateMenuItemRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetPosition() int32 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *UpdateMenuItemRequest) GetIsMain() bool {
	if x != nil && x.IsMain != nil {
		return *x.IsMain
	}
	return false
}

func (x *UpdateMenuItemRequest) GetDescriptionPostId() int32 {
	if x != nil && x.DescriptionPostId != nil {
		return *x.DescriptionPostId
	}
	return 0
}

type UpdateMenuItemMoveGroupUpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId     int32 `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	MenuItemId int32 `protobuf:"varint,2,opt,name=menuItemId,proto3" json:"menuItemId,omitempty"`
}

func (x *UpdateMenuItemMoveGroupUpRequest) Reset() {
	*x = UpdateMenuItemMoveGroupUpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMenuItemMoveGroupUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemMoveGroupUpRequest) ProtoMessage() {}

func (x *UpdateMenuItemMoveGroupUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemMoveGroupUpRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemMoveGroupUpRequest) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMenuItemMoveGroupUpRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *UpdateMenuItemMoveGroupUpRequest) GetMenuItemId() int32 {
	if x != nil {
		return x.MenuItemId
	}
	return 0
}

type DeleteMenuItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId     int32 `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	MenuItemId int32 `protobuf:"varint,2,opt,name=menuItemId,proto3" json:"menuItemId,omitempty"`
}

func (x *DeleteMenuItemRequest) Reset() {
	*x = DeleteMenuItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuItemRequest) ProtoMessage() {}

func (x *DeleteMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMenuItemRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *DeleteMenuItemRequest) GetMenuItemId() int32 {
	if x != nil {
		return x.MenuItemId
	}
	return 0
}

type GetMenuItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId int32 `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
}

func (x *GetMenuItemsRequest) Reset() {
	*x = GetMenuItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemsRequest) ProtoMessage() {}

func (x *GetMenuItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemsRequest.ProtoReflect.Descriptor instead.
func (*GetMenuItemsRequest) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{6}
}

func (x *GetMenuItemsRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

type GetMenuItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuItems []*MenuItem `protobuf:"bytes,1,rep,name=menuItems,proto3" json:"menuItems,omitempty"`
}

func (x *GetMenuItemsResponse) Reset() {
	*x = GetMenuItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemsResponse) ProtoMessage() {}

func (x *GetMenuItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemsResponse.ProtoReflect.Descriptor instead.
func (*GetMenuItemsResponse) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{7}
}

func (x *GetMenuItemsResponse) GetMenuItems() []*MenuItem {
	if x != nil {
		return x.MenuItems
	}
	return nil
}

type CreateMenuItemPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId                    int32   `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	MenuItemId                int32   `protobuf:"varint,2,opt,name=menuItemId,proto3" json:"menuItemId,omitempty"`
	PostId                    *int32  `protobuf:"varint,3,opt,name=postId,proto3,oneof" json:"postId,omitempty"`
	Position                  *int32  `protobuf:"varint,4,opt,name=position,proto3,oneof" json:"position,omitempty"`
	IsMenuItemDescriptionPost *bool   `protobuf:"varint,5,opt,name=isMenuItemDescriptionPost,proto3,oneof" json:"isMenuItemDescriptionPost,omitempty"`
	Title                     *string `protobuf:"bytes,6,opt,name=title,proto3,oneof" json:"title,omitempty"`
	ShortDescription          *string `protobuf:"bytes,7,opt,name=shortDescription,proto3,oneof" json:"shortDescription,omitempty"`
	ImageThumbnailId          *int32  `protobuf:"varint,8,opt,name=imageThumbnailId,proto3,oneof" json:"imageThumbnailId,omitempty"`
}

func (x *CreateMenuItemPostRequest) Reset() {
	*x = CreateMenuItemPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMenuItemPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuItemPostRequest) ProtoMessage() {}

func (x *CreateMenuItemPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuItemPostRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuItemPostRequest) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{8}
}

func (x *CreateMenuItemPostRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *CreateMenuItemPostRequest) GetMenuItemId() int32 {
	if x != nil {
		return x.MenuItemId
	}
	return 0
}

func (x *CreateMenuItemPostRequest) GetPostId() int32 {
	if x != nil && x.PostId != nil {
		return *x.PostId
	}
	return 0
}

func (x *CreateMenuItemPostRequest) GetPosition() int32 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

func (x *CreateMenuItemPostRequest) GetIsMenuItemDescriptionPost() bool {
	if x != nil && x.IsMenuItemDescriptionPost != nil {
		return *x.IsMenuItemDescriptionPost
	}
	return false
}

func (x *CreateMenuItemPostRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *CreateMenuItemPostRequest) GetShortDescription() string {
	if x != nil && x.ShortDescription != nil {
		return *x.ShortDescription
	}
	return ""
}

func (x *CreateMenuItemPostRequest) GetImageThumbnailId() int32 {
	if x != nil && x.ImageThumbnailId != nil {
		return *x.ImageThumbnailId
	}
	return 0
}

type UpdateMenuItemPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId        int32  `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	MenuItemId    int32  `protobuf:"varint,2,opt,name=menuItemId,proto3" json:"menuItemId,omitempty"`
	PostId        int32  `protobuf:"varint,3,opt,name=postId,proto3" json:"postId,omitempty"`
	NewMenuItemId *int32 `protobuf:"varint,4,opt,name=newMenuItemId,proto3,oneof" json:"newMenuItemId,omitempty"`
	Position      *int32 `protobuf:"varint,5,opt,name=position,proto3,oneof" json:"position,omitempty"`
}

func (x *UpdateMenuItemPostRequest) Reset() {
	*x = UpdateMenuItemPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMenuItemPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemPostRequest) ProtoMessage() {}

func (x *UpdateMenuItemPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemPostRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemPostRequest) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMenuItemPostRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *UpdateMenuItemPostRequest) GetMenuItemId() int32 {
	if x != nil {
		return x.MenuItemId
	}
	return 0
}

func (x *UpdateMenuItemPostRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *UpdateMenuItemPostRequest) GetNewMenuItemId() int32 {
	if x != nil && x.NewMenuItemId != nil {
		return *x.NewMenuItemId
	}
	return 0
}

func (x *UpdateMenuItemPostRequest) GetPosition() int32 {
	if x != nil && x.Position != nil {
		return *x.Position
	}
	return 0
}

type DeleteMenuItemPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId     int32 `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	MenuItemId int32 `protobuf:"varint,2,opt,name=menuItemId,proto3" json:"menuItemId,omitempty"`
	PostId     int32 `protobuf:"varint,3,opt,name=postId,proto3" json:"postId,omitempty"`
}

func (x *DeleteMenuItemPostRequest) Reset() {
	*x = DeleteMenuItemPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMenuItemPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuItemPostRequest) ProtoMessage() {}

func (x *DeleteMenuItemPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuItemPostRequest.ProtoReflect.Descriptor instead.
func (*DeleteMenuItemPostRequest) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMenuItemPostRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *DeleteMenuItemPostRequest) GetMenuItemId() int32 {
	if x != nil {
		return x.MenuItemId
	}
	return 0
}

func (x *DeleteMenuItemPostRequest) GetPostId() int32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type GetMenuItemPostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId     int32 `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	MenuItemId int32 `protobuf:"varint,2,opt,name=menuItemId,proto3" json:"menuItemId,omitempty"`
}

func (x *GetMenuItemPostsRequest) Reset() {
	*x = GetMenuItemPostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuItemPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemPostsRequest) ProtoMessage() {}

func (x *GetMenuItemPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemPostsRequest.ProtoReflect.Descriptor instead.
func (*GetMenuItemPostsRequest) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{11}
}

func (x *GetMenuItemPostsRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *GetMenuItemPostsRequest) GetMenuItemId() int32 {
	if x != nil {
		return x.MenuItemId
	}
	return 0
}

type GetMenuItemPostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuItemPosts []*MenuItemPost `protobuf:"bytes,1,rep,name=menuItemPosts,proto3" json:"menuItemPosts,omitempty"`
}

func (x *GetMenuItemPostsResponse) Reset() {
	*x = GetMenuItemPostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuItemPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemPostsResponse) ProtoMessage() {}

func (x *GetMenuItemPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemPostsResponse.ProtoReflect.Descriptor instead.
func (*GetMenuItemPostsResponse) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{12}
}

func (x *GetMenuItemPostsResponse) GetMenuItemPosts() []*MenuItemPost {
	if x != nil {
		return x.MenuItemPosts
	}
	return nil
}

type GetMenuItemPostsByMenuIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId int32 `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
}

func (x *GetMenuItemPostsByMenuIdRequest) Reset() {
	*x = GetMenuItemPostsByMenuIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuItemPostsByMenuIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemPostsByMenuIdRequest) ProtoMessage() {}

func (x *GetMenuItemPostsByMenuIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemPostsByMenuIdRequest.ProtoReflect.Descriptor instead.
func (*GetMenuItemPostsByMenuIdRequest) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{13}
}

func (x *GetMenuItemPostsByMenuIdRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

type GetMenuItemPostsByMenuIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuItemPosts []*MenuItemPost `protobuf:"bytes,1,rep,name=menuItemPosts,proto3" json:"menuItemPosts,omitempty"`
}

func (x *GetMenuItemPostsByMenuIdResponse) Reset() {
	*x = GetMenuItemPostsByMenuIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuItemPostsByMenuIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemPostsByMenuIdResponse) ProtoMessage() {}

func (x *GetMenuItemPostsByMenuIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemPostsByMenuIdResponse.ProtoReflect.Descriptor instead.
func (*GetMenuItemPostsByMenuIdResponse) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{14}
}

func (x *GetMenuItemPostsByMenuIdResponse) GetMenuItemPosts() []*MenuItemPost {
	if x != nil {
		return x.MenuItemPosts
	}
	return nil
}

type UpdateMenuPostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId     int32   `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	MenuItemId *int32  `protobuf:"varint,2,opt,name=menuItemId,proto3,oneof" json:"menuItemId,omitempty"`
	PostIds    []int32 `protobuf:"varint,3,rep,packed,name=postIds,proto3" json:"postIds,omitempty"`
}

func (x *UpdateMenuPostsRequest) Reset() {
	*x = UpdateMenuPostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMenuPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuPostsRequest) ProtoMessage() {}

func (x *UpdateMenuPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuPostsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuPostsRequest) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateMenuPostsRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *UpdateMenuPostsRequest) GetMenuItemId() int32 {
	if x != nil && x.MenuItemId != nil {
		return *x.MenuItemId
	}
	return 0
}

func (x *UpdateMenuPostsRequest) GetPostIds() []int32 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

type UpdateMenuPostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuItemPosts []*MenuItemPost `protobuf:"bytes,1,rep,name=menuItemPosts,proto3" json:"menuItemPosts,omitempty"`
}

func (x *UpdateMenuPostsResponse) Reset() {
	*x = UpdateMenuPostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMenuPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuPostsResponse) ProtoMessage() {}

func (x *UpdateMenuPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuPostsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMenuPostsResponse) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateMenuPostsResponse) GetMenuItemPosts() []*MenuItemPost {
	if x != nil {
		return x.MenuItemPosts
	}
	return nil
}

type GetMenuItemContentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuId     int32 `protobuf:"varint,1,opt,name=menuId,proto3" json:"menuId,omitempty"`
	MenuItemId int32 `protobuf:"varint,2,opt,name=menuItemId,proto3" json:"menuItemId,omitempty"`
}

func (x *GetMenuItemContentRequest) Reset() {
	*x = GetMenuItemContentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuItemContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemContentRequest) ProtoMessage() {}

func (x *GetMenuItemContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemContentRequest.ProtoReflect.Descriptor instead.
func (*GetMenuItemContentRequest) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{17}
}

func (x *GetMenuItemContentRequest) GetMenuId() int32 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *GetMenuItemContentRequest) GetMenuItemId() int32 {
	if x != nil {
		return x.MenuItemId
	}
	return 0
}

type GetMenuItemContentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuItemEntityGroups []*MenuItemEntityGroup `protobuf:"bytes,1,rep,name=menuItemEntityGroups,proto3" json:"menuItemEntityGroups,omitempty"`
	Content              []*EntityGroupContent  `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty"`
	EntityList           *EntityList            `protobuf:"bytes,3,opt,name=entityList,proto3" json:"entityList,omitempty"`
}

func (x *GetMenuItemContentResponse) Reset() {
	*x = GetMenuItemContentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menus_rpc_menu_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuItemContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemContentResponse) ProtoMessage() {}

func (x *GetMenuItemContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_menus_rpc_menu_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemContentResponse.ProtoReflect.Descriptor instead.
func (*GetMenuItemContentResponse) Descriptor() ([]byte, []int) {
	return file_services_menus_rpc_menu_proto_rawDescGZIP(), []int{18}
}

func (x *GetMenuItemContentResponse) GetMenuItemEntityGroups() []*MenuItemEntityGroup {
	if x != nil {
		return x.MenuItemEntityGroups
	}
	return nil
}

func (x *GetMenuItemContentResponse) GetContent() []*EntityGroupContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetMenuItemContentResponse) GetEntityList() *EntityList {
	if x != nil {
		return x.EntityList
	}
	return nil
}

var File_services_menus_rpc_menu_proto protoreflect.FileDescriptor

var file_services_menus_rpc_menu_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x73,
	0x2f, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x1a, 0x19, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x65,
	0x6e, 0x75, 0x73, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84,
	0x01, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49,
	0x6d, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x0b, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x49, 0x6d, 0x67, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x49, 0x6d, 0x67, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x22,
	0xad, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e,
	0x75, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x69, 0x73,
	0x4d, 0x61, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x06, 0x69, 0x73,
	0x4d, 0x61, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x69, 0x73, 0x4d, 0x61, 0x69, 0x6e, 0x22,
	0xb2, 0x02, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e,
	0x75, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x02, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x69, 0x73, 0x4d, 0x61, 0x69, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x03, 0x52, 0x06, 0x69, 0x73, 0x4d, 0x61, 0x69, 0x6e, 0x88, 0x01,
	0x01, 0x12, 0x31, 0x0a, 0x11, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x48, 0x04, 0x52, 0x11,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x69, 0x73, 0x4d, 0x61, 0x69, 0x6e, 0x42, 0x14,
	0x0a, 0x12, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x20, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65,
	0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x6f, 0x76, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x55,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e, 0x75,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64,
	0x22, 0x4f, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e,
	0x75, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x22, 0x2d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e, 0x75,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64,
	0x22, 0x42, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x09, 0x6d, 0x65, 0x6e, 0x75,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x6d, 0x65, 0x6e, 0x75, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0xbb, 0x03, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65,
	0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x06, 0x70, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x70, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x41, 0x0a, 0x19, 0x69, 0x73, 0x4d, 0x65,
	0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x6f, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x19, 0x69,
	0x73, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x73, 0x74, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x10, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x04, 0x52, 0x10, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x10, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x05, 0x52, 0x10, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e,
	0x61, 0x69, 0x6c, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x70, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x1c, 0x0a, 0x1a, 0x5f, 0x69, 0x73, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x13, 0x0a,
	0x11, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c,
	0x49, 0x64, 0x22, 0xd6, 0x01, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6e,
	0x75, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x6e, 0x75,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x65,
	0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64,
	0x12, 0x29, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0d, 0x6e, 0x65, 0x77, 0x4d, 0x65,
	0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x10, 0x0a, 0x0e,
	0x5f, 0x6e, 0x65, 0x77, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x42, 0x0b,
	0x0a, 0x09, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6b, 0x0a, 0x19, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e, 0x75,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d,
	0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x52, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0d, 0x6d, 0x65, 0x6e, 0x75, 0x49,
	0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x0d, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x22,
	0x39, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f,
	0x73, 0x74, 0x73, 0x42, 0x79, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x20, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x42, 0x79,
	0x4d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36,
	0x0a, 0x0d, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49,
	0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x0d, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65,
	0x6d, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x7e, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x6e, 0x75, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0a, 0x6d, 0x65, 0x6e, 0x75,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a,
	0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07,
	0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x73, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6d, 0x65, 0x6e, 0x75,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x6e, 0x75, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x36, 0x0a, 0x0d, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65,
	0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x0d, 0x6d, 0x65, 0x6e, 0x75,
	0x49, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x53, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0xcb,
	0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a,
	0x14, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x14, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x30, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x0a,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x2a, 0x5a, 0x28,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x2d, 0x6d,
	0x65, 0x64, 0x6f, 0x2f, 0x74, 0x61, 0x6c, 0x65, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x2d, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_menus_rpc_menu_proto_rawDescOnce sync.Once
	file_services_menus_rpc_menu_proto_rawDescData = file_services_menus_rpc_menu_proto_rawDesc
)

func file_services_menus_rpc_menu_proto_rawDescGZIP() []byte {
	file_services_menus_rpc_menu_proto_rawDescOnce.Do(func() {
		file_services_menus_rpc_menu_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_menus_rpc_menu_proto_rawDescData)
	})
	return file_services_menus_rpc_menu_proto_rawDescData
}

var file_services_menus_rpc_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_services_menus_rpc_menu_proto_goTypes = []interface{}{
	(*UpdateMenuRequest)(nil),                // 0: pb.UpdateMenuRequest
	(*GetMenuRequest)(nil),                   // 1: pb.GetMenuRequest
	(*CreateMenuItemRequest)(nil),            // 2: pb.CreateMenuItemRequest
	(*UpdateMenuItemRequest)(nil),            // 3: pb.UpdateMenuItemRequest
	(*UpdateMenuItemMoveGroupUpRequest)(nil), // 4: pb.UpdateMenuItemMoveGroupUpRequest
	(*DeleteMenuItemRequest)(nil),            // 5: pb.DeleteMenuItemRequest
	(*GetMenuItemsRequest)(nil),              // 6: pb.GetMenuItemsRequest
	(*GetMenuItemsResponse)(nil),             // 7: pb.GetMenuItemsResponse
	(*CreateMenuItemPostRequest)(nil),        // 8: pb.CreateMenuItemPostRequest
	(*UpdateMenuItemPostRequest)(nil),        // 9: pb.UpdateMenuItemPostRequest
	(*DeleteMenuItemPostRequest)(nil),        // 10: pb.DeleteMenuItemPostRequest
	(*GetMenuItemPostsRequest)(nil),          // 11: pb.GetMenuItemPostsRequest
	(*GetMenuItemPostsResponse)(nil),         // 12: pb.GetMenuItemPostsResponse
	(*GetMenuItemPostsByMenuIdRequest)(nil),  // 13: pb.GetMenuItemPostsByMenuIdRequest
	(*GetMenuItemPostsByMenuIdResponse)(nil), // 14: pb.GetMenuItemPostsByMenuIdResponse
	(*UpdateMenuPostsRequest)(nil),           // 15: pb.UpdateMenuPostsRequest
	(*UpdateMenuPostsResponse)(nil),          // 16: pb.UpdateMenuPostsResponse
	(*GetMenuItemContentRequest)(nil),        // 17: pb.GetMenuItemContentRequest
	(*GetMenuItemContentResponse)(nil),       // 18: pb.GetMenuItemContentResponse
	(*MenuItem)(nil),                         // 19: pb.MenuItem
	(*MenuItemPost)(nil),                     // 20: pb.MenuItemPost
	(*MenuItemEntityGroup)(nil),              // 21: pb.MenuItemEntityGroup
	(*EntityGroupContent)(nil),               // 22: pb.EntityGroupContent
	(*EntityList)(nil),                       // 23: pb.EntityList
}
var file_services_menus_rpc_menu_proto_depIdxs = []int32{
	19, // 0: pb.GetMenuItemsResponse.menuItems:type_name -> pb.MenuItem
	20, // 1: pb.GetMenuItemPostsResponse.menuItemPosts:type_name -> pb.MenuItemPost
	20, // 2: pb.GetMenuItemPostsByMenuIdResponse.menuItemPosts:type_name -> pb.MenuItemPost
	20, // 3: pb.UpdateMenuPostsResponse.menuItemPosts:type_name -> pb.MenuItemPost
	21, // 4: pb.GetMenuItemContentResponse.menuItemEntityGroups:type_name -> pb.MenuItemEntityGroup
	22, // 5: pb.GetMenuItemContentResponse.content:type_name -> pb.EntityGroupContent
	23, // 6: pb.GetMenuItemContentResponse.entityList:type_name -> pb.EntityList
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_services_menus_rpc_menu_proto_init() }
func file_services_menus_rpc_menu_proto_init() {
	if File_services_menus_rpc_menu_proto != nil {
		return
	}
	file_services_menus_menu_proto_init()
	file_services_entities_entity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_services_menus_rpc_menu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMenuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMenuItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMenuItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMenuItemMoveGroupUpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMenuItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMenuItemPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMenuItemPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMenuItemPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuItemPostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuItemPostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuItemPostsByMenuIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuItemPostsByMenuIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMenuPostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMenuPostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuItemContentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menus_rpc_menu_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuItemContentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_services_menus_rpc_menu_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_services_menus_rpc_menu_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_services_menus_rpc_menu_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_services_menus_rpc_menu_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_services_menus_rpc_menu_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_services_menus_rpc_menu_proto_msgTypes[15].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_menus_rpc_menu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_menus_rpc_menu_proto_goTypes,
		DependencyIndexes: file_services_menus_rpc_menu_proto_depIdxs,
		MessageInfos:      file_services_menus_rpc_menu_proto_msgTypes,
	}.Build()
	File_services_menus_rpc_menu_proto = out.File
	file_services_menus_rpc_menu_proto_rawDesc = nil
	file_services_menus_rpc_menu_proto_goTypes = nil
	file_services_menus_rpc_menu_proto_depIdxs = nil
}
